### ISSUE TITLE
SSDT-FAN-MOD/READ is based on FakeSMC. How to adapt VirtualSMC?

### ISSUE THREAD

**Issue by Autines** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#22]

**Comment by hieplpvip** [comment]
Sadly, there's no way to do it now. But it seems that eventually VirtualSMC will support FakeSMC's plugins, maybe we'll be able to do it then

**Comment by xick** [comment]
First of all, thanks for all your efforts. I'm now having a 99% working hackintosh machine. Everything works well (I now even have 100% working audio with the last Jack_fix provided by mirone for alc294) except for custom fan read/control. 
With previous build of my own I could at least read RPM with fakeSMC, but due to this conflict with virtualSMC i can't do this anymore. However custom fan control didn't work anyway, due to different methods in DSDT provided for read/control of the fans in newer laptops (or BIOS?)
So even with FakeSMC would be impossible to have custom fan control with no change in original ssdt-fan.dsl code or dsdt. 
if you want to have a look here's my DSDT, where you can see the different methods used in my configuration (UX430UNR bios 305)
[DSDT.aml.zip](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/2775681/DSDT.aml.zip)
@hieplpvip  I took the chance to tell you to advice users to be aware of bios update, in fact last bios (309) caused my hackintosh to not to start and I had to revert to a previous version.
Moreover, I had to disable some kexts to enter to the installer and until completing the installation process, as I remember were VoodooI2C ones.

**Comment by hieplpvip** [comment]
@xick Where is the Jack_fix by Mirone?

**Comment by xick** [comment]
@hieplpvip http://olarila.com/forum/viewtopic.php?f=45&p=72237
I don't know if it's the same thing as ALCPlugFix, but my jack plug worked only after I uninstalled ALCPlugFix and installed this. Yesterday I experienced some random audio disappear, so I also changed layout (12 instead of 13) and injected with Clover instead SSDT (I also uninstalled SSDT-AppleALC because it seems unnecessary). I'm testing right now this configuration, I will let you know if I experience issues.
EDIT: There's no need to change layout or configuration, audio stop working only when I enter Clover after a reboot from Windows, so I need to shutdown and restart in this case. I can confirm that with ALC294 everything works good (only Jack_fix may need )

**Comment by aufuk1** [comment]
I can read the fan speed with OC 0.8.3 and Fakecmsc3.
https://github.com/CloverHackyColor/FakeSMC3_with_plugins
--
How can I define fan speed with OC 0.8.3 and Virtualsmc?
https://github.com/acidanthera/VirtualSMC

![image jpeg a3da8408519f5e7f0839c2b81014ee71](https://user-images.githubusercontent.com/13665547/183297389-d28dd4ad-68ef-4ce0-be73-0278b138855c.jpeg)

[SSDT-FANREAD.aml.zip](https://github.com/hieplpvip/Asus-Zenbook-Hackintosh/files/9277003/SSDT-FANREAD.aml.zip)
