### ISSUE TITLE
Wi-Fi issue on UX430UA

### ISSUE THREAD

**Issue by orditeck** [hieplpvip/ASUS-ZENBOOK-UX410-HACKINTOSH#28]
**What is your laptop?**
UX430UA

**Which version of macOS are you using?**
10.14.1

**Describe the problems**
The Wi-Fi turns off by itself. I can't turn it on again, I tried to turn it on using the icon in the top menu and in the network settings. I have to reboot to get it to work again. The bluetooth, however, keeps working (and is on the same hardware/card).

**Attach output from [gen_debug](https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/)**
https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/2559765/debug_6182.zip

**Additional context**
I have the DW1560 card installed correctly.
BCM94352Z 802.11a/b/g/n/ac WLAN & Bluetooth 4.0 M.2 NGFF Mini Card, D P/N DW1560

**Comment by Vmonheros** [comment]
Hi.

You can chose to use this injector in replacement from RehabMan kexts BRCMFirmwareRepo and BRCMPatchRAM2 (this injector came for him from previous version). It works well with DW1560 and it's lighter !

Have a try. You can inject it from Clover or add it to L/E.

[BrcmBluetoothInjector.kext.zip](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH/files/2760608/BrcmBluetoothInjector.kext.zip)

**Comment by orditeck** [comment]
Will try tonight. Thank you very mcuh @Vmonheros! Mon héro! 😄

**Comment by Vmonheros** [comment]
Note that it is a simple injector.

It relies on OSX capability that came on release 10.10 to upload bluetooth firmware to cards that need them (with and internal OSX firmware database). Thats works well with DW1560 and rely on default OSX capability.

So it avoid RehabMan kexts (that works with more Bluethooth card for sure !) and is less than 20 ko... Far away form the 2.5 Mo for Rehabman firmware database.

**Comment by orditeck** [comment]
@Vmonheros, should I replace any kext I currently have but yours? Maybe `AirportBrcmFixup.kext`?

```
➜  ~ ls /Volumes/EFI/EFI/CLOVER/kexts/Other 
ACPIBatteryManager.kext      LiluFriend.kext
ACPIPoller.kext              NullEthernet.kext
AirportBrcmFixup.kext        SMCProcessor.kext
AppleALC.kext                USBInjectAll.kext
AppleBacklightFixup.kext     VirtualSMC.kext
AsusSMC.kext                 VoodooI2C.kext
BT4LEContiunityFixup.kext    VoodooI2CHID.kext
FakePCIID.kext               VoodooPS2Controller.kext
FakePCIID_Broadcom_WiFi.kext WhateverGreen.kext
Lilu.kext
```

**Comment by hieplpvip** [comment]
@orditeck If you want to try @Vmonheros 's kext, remove `BrcmPatchRAM2` and `BrcmFirmwareRepo` in `/Library/Extensions`. Don't forget to rebuild kextcache.

Honestly, I don't understand why you want to try that kext, since it's for Bluetooth, and what you wanna fix is Wifi. I don't see anything wrong with Wifi in your debug files, not sure what your problem is.

One more thing, `AirportBrcmFixup` is for Wifi, not Bluetooth. Deleting it will break your wifi.

**Comment by Vmonheros** [comment]
@ hieplpvip

You're right. But as the bluetooth and wifi are provided with the same card, I want to have a try (even if normally they might be no interference). As it can't hurt and the injector is far smaller in size, it's might not be worst ;).

**Comment by hieplpvip** [comment]
@Vmonheros where did you get that kext?

**Comment by orditeck** [comment]
I used the laptop the several hours yesterday and it did not happen. Using it this morning and it's not happening. Before, it was happening at least once in ~45min of use.

Would that be a hardware issue then? What could cause the Wi-Fi to just turn off itself?

If/when it happens again, I'll make a new gen_debug

**Comment by Vmonheros** [comment]
Hi.

The Kext came from RehabMan. Long time ago when he compiled it. I used it because it works with DW1560, is only few kb and works with "native" OS X process.

https://github.com/RehabMan/OS-X-BrcmPatchRAM

###BrcmBluetoothInjector.kext

To be used for OS X 10.11 or newer.

This kext is a simple injector... it does not contain a firmware uploader. Try this kext if you wish to see if your device will work without a firmware uploader.

Do not use any of the other kexts (BrcmPatchRAM, BrcmPatchRAM2, BrcmFirmwareRepo, or BrcmFirmwareData) with this kext.

This kext is not provided in the distribution ZIP. You can build it if you wish to try it. It was removed as it presense was causing confusion for those that don't read carefully and didn't install the preferred kexts correctly. It is not currently being updated with new devices. If yours is not present, edit the Info.plist as needed.

**Comment by orditeck** [comment]
I've got the same issue yesterday morning. I rebooted and the Wi-Fi wouldn't turn on, usually the Wi-Fi would work after a reboot. I rebooted again and now it says I have no Wi-Fi hardware. The Bluetooth works great. Which leads me to think that it could be an hardware issue... What do you think?

**Comment by Vmonheros** [comment]
As the DW1560 is not so expensive, it's worth a try to buy a new one. As you're the only one with this issue, there's great chance that it is an hardware issue.

I've just received my UX430 UAR. I will install it with OS X. I'm surprised as my UX430UA has got an ELAN 1300, and the UAR an Elan 1200 ??? The good thing is that the 2 have got a Chi Mei panel (and not the crapy BAO as we've got on some UAR)

**Comment by Piero512** [comment]
I've seen wifi issues when you only connect one of the two antenna ports that the DW1560 has.

**Comment by orditeck** [comment]
Both antenna were tightly connected but I disconnected/reconnected them and booted just to make sure and still no Wi-Fi. Changed the DW1560 card from one ordered on Amazon (instead of Aliexpress). Wi-Fi works well now...!!!! So it seems like it was the card after all! Thanks for your help guys.
